function [r, y_pred, y_test, x_test] = run_trf_encoding(x, y, fs, par_trf)

assert(size(y,1) == size(x,1), ...
    'y has %d samples and X has %d', size(y,1), size(x,1))

% ------ crossvalidate lambda parameter ------

r = nan(1, par_trf.n_cv_folds); 

for i_test_fold=1:par_trf.n_cv_folds

    [x_train, y_train, x_test, y_test] = mTRFpartition(x, y,...
                                                par_trf.n_cv_folds,...
                                                i_test_fold);

    % Run fast cross-validation
    cv = mTRFcrossval(x_train, y_train, fs, ...
                      par_trf.direction, ...
                      par_trf.tmin, ...
                      par_trf.tmax, ...
                      par_trf.lambdas, ...
                      'fast', 0,...
                      'method', 'Tikhonov', ...
                      'verbose', 0);

    % Get optimal hyperparameters
    [rmax, idx] = max(mean(mean(cv.r), 3));
    lambda = par_trf.lambdas(idx);

    model = mTRFtrain(x_train, y_train, ...
                      fs, par_trf.direction, ...
                      par_trf.tmin,...
                      par_trf.tmax, ...
                      lambda, ...
                      'method','Tikhonov', ...
                      'verbose', 0);

   [y_pred, test] = mTRFpredict(x_test, y_test, model, ...
                              'zeropad',1, 'verbose', 0);

   r(i_test_fold) = test.r; 

end

